# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shubham Garg
email: me@shubhamgarg.net
description: > # this means to ignore newlines until "baseurl:"
  My blog, my stuff!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shubhamgarg.net" # the base hostname & protocol for your site
twitter_username: shubham15
github_username:  shubhamg15

# Build settings
markdown: kramdown

theme: jekyll-theme-slate